### PR TITLE
US_1 and BrowserUtils and HomePage classes update

### PR DESCRIPTION
**Pull request by MedSdiri**

### CODE REVIEW

**Comment by MedSdiri** [comment]
ca

**Comment by GuvanchH** [comment]
Looks Good

**Comment by ripsupra** [comment]
nice

**Review by AzadBatch21 — APPROVED** [review]

**Review by ripsupra — APPROVED** [review]
nice job mane

**Review by GuvanchH — APPROVED** [review]
Nice

**Pull request merged**
